# true რომ გამოვიტანოთ print(true and true)
# false რომ გამოიტანოს დავწერთ print(false and false)
# true print(true or false)
# false print(false or false)
print(10 > 5)
print(20 > 15)
print(30 > 20)
print(true and false)
print(false and true)
print(true and true)
print(false or true)
print(true or true)
print(true false)